# Generated by Django 5.2.8 on 2025-11-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riazi', '0002_riazi_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='riazi',
            name='rank_country',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='رتبه کشوری'),
        ),
    ]
