# Generated by Django 5.2.8 on 2025-11-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riazi', '0003_riazi_rank_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='riazi',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر'),
        ),
    ]
