# Generated by Django 5.2.8 on 2025-11-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tajrobi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tajrobi',
            name='code',
        ),
        migrations.RemoveField(
            model_name='tajrobi',
            name='name',
        ),
        migrations.AddField(
            model_name='tajrobi',
            name='clue',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='رشته دانشگاهی'),
        ),
        migrations.AddField(
            model_name='tajrobi',
            name='period',
            field=models.CharField(blank=True, max_length=22, null=True, verbose_name='دوره'),
        ),
        migrations.AddField(
            model_name='tajrobi',
            name='rank_1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='رتبه منطقه 1'),
        ),
        migrations.AddField(
            model_name='tajrobi',
            name='rank_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='رتبه منطقه 2'),
        ),
        migrations.AddField(
            model_name='tajrobi',
            name='rank_25_percentage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='رتبه سهیمه 25 درصد'),
        ),
        migrations.AddField(
            model_name='tajrobi',
            name='rank_3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='رتبه منطقه 3'),
        ),
        migrations.AddField(
            model_name='tajrobi',
            name='rank_5_percentage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='رتبه سهمیه 5 درصد'),
        ),
        migrations.AddField(
            model_name='tajrobi',
            name='reshte',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='رشته تحصیلی'),
        ),
        migrations.AddField(
            model_name='tajrobi',
            name='univercity',
            field=models.CharField(blank=True, help_text='نام دانشگاه پذیرفته شده', max_length=100, null=True, verbose_name='دانشگاه'),
        ),
    ]
