# Generated by Django 5.2.8 on 2025-11-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ensani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reshte', models.CharField(blank=True, max_length=10, null=True, verbose_name='رشته تحصیلی')),
                ('clue', models.CharField(blank=True, max_length=10, null=True, verbose_name='رشته دانشگاهی')),
                ('univercity', models.CharField(blank=True, help_text='نام دانشگاه پذیرفته شده', max_length=100, null=True, verbose_name='دانشگاه')),
                ('period', models.CharField(blank=True, max_length=22, null=True, verbose_name='دوره')),
                ('rank_1', models.PositiveIntegerField(blank=True, null=True, verbose_name='رتبه منطقه 1')),
                ('rank_2', models.PositiveIntegerField(blank=True, null=True, verbose_name='رتبه منطقه 2')),
                ('rank_3', models.PositiveIntegerField(blank=True, null=True, verbose_name='رتبه منطقه 3')),
                ('rank_5_percentage', models.PositiveIntegerField(blank=True, null=True, verbose_name='رتبه سهمیه 5 درصد')),
                ('rank_25_percentage', models.PositiveIntegerField(blank=True, null=True, verbose_name='رتبه سهیمه 25 درصد')),
            ],
        ),
    ]
