# Generated by Django 5.2.8 on 2025-11-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensani', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensani',
            name='source',
            field=models.CharField(choices=[('local', 'اکسل\u200c\u200cها'), ('kanon', 'کانون'), ('hiva', 'هیوا')], default='', max_length=10, verbose_name='منبع : '),
            preserve_default=False,
        ),
    ]
